#!/bin/bash
echo "Starting..."

ROOTDIR="/var/www/html/Database/Backup"
YEAR=`date +%Y`
MONTH=`date +%m`
DAY=`date +%d`
HOUR=`date +%H`
SERVER="mysql.local"
BLACKLIST="information_schema performance_schema mysql sys"

if [ ! -d "$ROOTDIR/$DAY-$MONTH-$YEAR" ]; then
  mkdir -p "$ROOTDIR/$DAY-$MONTH-$YEAR"
fi

echo "running dump"

dblist=`mysql -uroot -pK@h0India -e "show databases" | sed -n '2,$ p'`
for db in $dblist;
do
    echo "Backuping $db"
    isBl=`echo $BLACKLIST | grep $db`

    if [ -z "$isBl" ]; then
       mysqldump -uroot -pK@h0India --single-transaction --routines --triggers $db | gzip --best > "$ROOTDIR/$DAY-$MONTH-$YEAR/$db.sql.gz"
       echo "Backup $db ends with return code $?"
    else
       echo "Database $db is on blacklist, skip"
    fi
done

echo "dump completed"
