#!/bin/bash

declare -A backlistArray

echo "Starting..."

ROOTDIR="/var/www/html/Database/Backup/Backups"
YEAR=`date +%Y`
MONTH=`date +%m`
DAY=`date +%d`
HOUR=`date +%H`
SERVER="mysql.local"
# BLACKLIST="information_schema performance_schema mysql sys KaHO_DEV KaHO_DEV_Basic KaHO_DEV_Old LIFE_Demo_Basic Demo"

backlistArray=( ['information_schema']=1 ['performance_schema']=1 ['mysql']=1 ['sys']=1 ['KaHO_DEV']=1 ['KaHO_DEV_Basic']=1 ['KaHO_DEV_Old']=1 ['LIFE_Demo_Basic']=1 ['Demo']=1 )

sshpass -p 'k@h02016' ssh kahoadmin@52.187.64.172 '[ -d $ROOTDIR/$DAY-$MONTH-$YEAR ]'
if [[ $? -eq 0 ]]
then
    echo 'Directory exists'
else
    sshpass -p 'k@h02016' ssh kahoadmin@52.187.64.172  "mkdir -p $ROOTDIR/$DAY-$MONTH-$YEAR"
fi

echo "running dump"

dblist=`mysql -uroot -pK@h0India -e "show databases" | sed -n '2,$ p'`
for db in $dblist;
do
    echo "Backing up $db"

    if [[ ${backlistArray[$db]} ]]; then
       echo  "Database $db is on blacklist, skip"
    else
       mysqldump -uroot -pK@h0India --single-transaction --routines --triggers $db | gzip --best |sshpass -p 'k@h02016' ssh kahoadmin@52.187.64.172 "cat > $ROOTDIR/$DAY-$MONTH-$YEAR/$db.sql.gz"
    fi
done

echo "dump completed in folder $ROOTDIR/$DAY-$MONTH-$YEAR"