#!/bin/bash

PATH='/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games'

ROOTDIR="/var/www/html/Database/Backup/Backups/*"

find $ROOTDIR -mtime +7 | xargs rm -f -r
