#!/bin/bash
if [ -z $1 ]; then
read -p "please enter the database" db
if [ -z $db ]; then
echo "please enter the db"
exit;
fi
else
db=$1
fi
mysql -u root -pK@h0India  -D $db < changes.sql
echo "over"
